services:
  - type: web
    name: quant-alpha
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TWELVE_DATA_API_KEY
        sync: false
      - key: MARKET_INTERVAL
        value: 15min
      - key: FRONTEND_ORIGIN
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_WEBHOOK_ID
        sync: false
