import "dotenv/config";
import express from "express";
import cors from "cors";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import bcrypt from "bcryptjs";
import pg from "pg";
const { Pool } = pg;

const app = express();
const PORT = Number(process.env.PORT || 10000);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TD_KEY = process.env.TWELVE_DATA_API_KEY;
const TD_BASE = "https://api.twelvedata.com";
const APP_URL = process.env.APP_URL || `http://localhost:${PORT}`;
const SESSION_SECRET = process.env.SESSION_SECRET || "development-only-change-me";
const DATABASE_URL = process.env.DATABASE_URL;
const useDb = Boolean(DATABASE_URL);
const fileDir = path.join(__dirname, ".data");
const membersFile = path.join(fileDir, "members.json");
if (!useDb) { fs.mkdirSync(fileDir, {recursive:true}); if(!fs.existsSync(membersFile)) fs.writeFileSync(membersFile, JSON.stringify({users:[]},null,2)); }
const pool = useDb ? new Pool({connectionString:DATABASE_URL, ssl: process.env.DATABASE_URL?.includes("render.com") ? {rejectUnauthorized:false}:undefined, max:5}) : null;

const INSTRUMENTS={
 XAUUSD:{name:"Gold",dataSymbol:process.env.TD_XAUUSD_SYMBOL||"XAU/USD",chart:"OANDA:XAUUSD",decimals:2},
 EURUSD:{name:"EUR/USD",dataSymbol:"EUR/USD",chart:"OANDA:EURUSD",decimals:5},
 GBPUSD:{name:"GBP/USD",dataSymbol:"GBP/USD",chart:"OANDA:GBPUSD",decimals:5},
 USDJPY:{name:"USD/JPY",dataSymbol:"USD/JPY",chart:"OANDA:USDJPY",decimals:3},
 AUDUSD:{name:"AUD/USD",dataSymbol:"AUD/USD",chart:"OANDA:AUDUSD",decimals:5},
 NAS100:{name:"Nasdaq 100",dataSymbol:process.env.TD_NAS100_SYMBOL||"NDX",chart:"NASDAQ:NDX",decimals:2},
 US30:{name:"Dow Jones 30",dataSymbol:process.env.TD_US30_SYMBOL||"DJI",chart:"DJ:DJI",decimals:2},
 JPN225:{name:"Japan 225",dataSymbol:process.env.TD_JPN225_SYMBOL||"N225",chart:"TVC:NI225",decimals:0}
};

function b64(s){return Buffer.from(s).toString("base64url")}
function sign(s){return crypto.createHmac("sha256",SESSION_SECRET).update(s).digest("base64url")}
function issueSession(u){const body=b64(JSON.stringify({id:u.id,email:u.email,plan:u.plan,status:u.status,exp:Date.now()+1000*60*60*24*30}));return `${body}.${sign(body)}`}
function verifySession(token){try{const [body,sig]=String(token||"").split(".");if(!body||!sig)return null;const a=Buffer.from(sig),b=Buffer.from(sign(body));if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;const p=JSON.parse(Buffer.from(body,"base64url").toString());return p.exp>Date.now()?p:null}catch{return null}}
async function auth(req,res,next){const s=verifySession((req.headers.authorization||"").replace(/^Bearer\s+/i,""));if(!s)return res.status(401).json({error:"Please log in."});let u=await getUserById(s.id);if(!u)return res.status(401).json({error:"Account not found."});req.user=u;next()}
async function requireActive(req,res,next){await auth(req,res,()=>{if(req.user.status!=="active")return res.status(403).json({error:"Active membership required."});next()})}

async function initDb(){if(!useDb)return;await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,plan TEXT NOT NULL DEFAULT 'none',status TEXT NOT NULL DEFAULT 'pending',paypal_order_id TEXT, paypal_subscription_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS users_email_idx ON users(email);`)}
function fileDb(){return JSON.parse(fs.readFileSync(membersFile,"utf8"))}
function saveFileDb(d){fs.writeFileSync(membersFile,JSON.stringify(d,null,2))}
async function getUserByEmail(email){email=email.toLowerCase().trim();if(useDb){const r=await pool.query("SELECT * FROM users WHERE email=$1",[email]);return r.rows[0]||null}return fileDb().users.find(x=>x.email===email)||null}
async function getUserById(id){if(useDb){const r=await pool.query("SELECT * FROM users WHERE id=$1",[id]);return r.rows[0]||null}return fileDb().users.find(x=>String(x.id)===String(id))||null}
async function createUser(email,password){const hash=await bcrypt.hash(password,12);if(useDb){const r=await pool.query("INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING *",[email,hash]);return r.rows[0]}const d=fileDb();const u={id:crypto.randomUUID(),email,password_hash:hash,plan:"none",status:"pending",created_at:new Date().toISOString()};d.users.push(u);saveFileDb(d);return u}
async function updateUser(id,fields){if(useDb){const keys=Object.keys(fields);const sets=keys.map((k,i)=>`${k}=$${i+1}`).join(",");const vals=keys.map(k=>fields[k]);vals.push(id);const r=await pool.query(`UPDATE users SET ${sets},updated_at=NOW() WHERE id=$${vals.length} RETURNING *`,vals);return r.rows[0]}const d=fileDb();const i=d.users.findIndex(x=>String(x.id)===String(id));if(i<0)return null;d.users[i]={...d.users[i],...fields,updated_at:new Date().toISOString()};saveFileDb(d);return d.users[i]}

app.use(cors({origin:(process.env.CORS_ORIGIN||"").split(",").map(x=>x.trim()).filter(Boolean).length?(process.env.CORS_ORIGIN||"").split(",").map(x=>x.trim()):true}));
app.use(express.json({limit:"1mb"}));
app.use(express.static(path.join(__dirname,"public")));
app.use("/downloads",express.static(path.join(__dirname,"docs")));
app.use("/certificates",express.static(path.join(__dirname,"certificates")));

async function td(endpoint,params={}){if(!TD_KEY)throw new Error("TWELVE_DATA_API_KEY is not configured on the server.");const u=new URL(TD_BASE+endpoint);for(const [k,v] of Object.entries({...params,apikey:TD_KEY}))u.searchParams.set(k,String(v));const r=await fetch(u);const j=await r.json();if(!r.ok||j.status==="error"||j.code)throw new Error(j.message||`Twelve Data ${r.status}`);return j}
function nums(rows,key){return rows.map(x=>Number(x[key])).filter(Number.isFinite).reverse()}
function ema(v,p){if(v.length<p)return null;const k=2/(p+1);let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
function rsi(v,p=14){if(v.length<p+1)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}return al===0?100:100-100/(1+ag/al)}
function atr(rows,p=14){const h=nums(rows,"high"),l=nums(rows,"low"),c=nums(rows,"close"),tr=[];for(let i=1;i<h.length;i++)tr.push(Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1])));return tr.length<p?null:tr.slice(-p).reduce((a,b)=>a+b,0)/p}
function adx(rows,p=14){if(rows.length<p*2+5)return null;const h=nums(rows,"high"),l=nums(rows,"low"),c=nums(rows,"close"),tr=[],pd=[],md=[];for(let i=1;i<h.length;i++){const up=h[i]-h[i-1],dn=l[i-1]-l[i];tr.push(Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1])));pd.push(up>dn&&up>0?up:0);md.push(dn>up&&dn>0?dn:0)}let a=tr.slice(0,p).reduce((x,y)=>x+y,0)/p,pp=pd.slice(0,p).reduce((x,y)=>x+y,0)/p,mm=md.slice(0,p).reduce((x,y)=>x+y,0)/p;const dx=[];for(let i=p;i<tr.length;i++){a=(a*(p-1)+tr[i])/p;pp=(pp*(p-1)+pd[i])/p;mm=(mm*(p-1)+md[i])/p;const dip=100*pp/a,dim=100*mm/a;dx.push(100*Math.abs(dip-dim)/Math.max(dip+dim,1e-9))}return dx.length<p?null:dx.slice(-p).reduce((x,y)=>x+y,0)/p}
function macd(v){const a=ema(v,12),b=ema(v,26);return a==null||b==null?null:a-b}
function bb(v,p=20,m=2){if(v.length<p)return null;const s=v.slice(-p),mid=s.reduce((a,b)=>a+b,0)/p,sd=Math.sqrt(s.reduce((a,b)=>a+(b-mid)**2,0)/p);return{middle:mid,upper:mid+m*sd,lower:mid-m*sd}}
function swings(rows,n=50){const h=nums(rows,"high").slice(-n),l=nums(rows,"low").slice(-n),highs=[],lows=[];for(let i=2;i<h.length-2;i++){if(h[i]>h[i-1]&&h[i]>h[i-2]&&h[i]>=h[i+1]&&h[i]>=h[i+2])highs.push(h[i]);if(l[i]<l[i-1]&&l[i]<l[i-2]&&l[i]<=l[i+1]&&l[i]<=l[i+2])lows.push(l[i])}return{highs,lows}}
function pattern(rows){const r=rows.slice(-3).map(x=>({o:+x.open,h:+x.high,l:+x.low,c:+x.close}));if(r.length<2)return"None";const a=r.at(-2),b=r.at(-1),body=Math.abs(b.c-b.o),range=Math.max(b.h-b.l,1e-9),upper=b.h-Math.max(b.o,b.c),lower=Math.min(b.o,b.c)-b.l,bull=b.c>b.o,bear=b.c<b.o;if(bull&&a.c<a.o&&b.o<=a.c&&b.c>=a.o)return"Bullish engulfing";if(bear&&a.c>a.o&&b.o>=a.c&&b.c<=a.o)return"Bearish engulfing";if(lower>body*2&&upper<body*.8)return"Hammer / rejection";if(upper>body*2&&lower<body*.8)return"Shooting star / rejection";if(body/range<.12)return"Doji";if(body/range>.65)return bull?"Strong bullish candle":"Strong bearish candle";return"None"}
function analyze(rows){const v=nums(rows,"close"),price=v.at(-1),e20=ema(v,20),e50=ema(v,50),e200=ema(v,200),rv=rsi(v),ax=adx(rows),a=atr(rows),mc=macd(v),bands=bb(v),sw=swings(rows),pat=pattern(rows);let score=0,reasons=[];const bull=(e50&&price>e50)||(rv!=null&&rv>50)||(mc!=null&&mc>0);const direction=bull?"BUY":"SELL";if(e20&&e50){if((price>e20&&e20>e50)||(price<e20&&e20<e50)){score+=20;reasons.push("EMA 20/50 alignment agrees with direction")}}if(e50&&e200&&((price>e50&&e50>e200)||(price<e50&&e50<e200))){score+=15;reasons.push("EMA 50/200 trend alignment agrees")};if(rv!=null&&((direction==="BUY"&&rv>=52&&rv<=70)||(direction==="SELL"&&rv>=30&&rv<=48))){score+=15;reasons.push(`RSI ${rv.toFixed(1)} supports the setup`)}if(mc!=null&&((direction==="BUY"&&mc>0)||(direction==="SELL"&&mc<0))){score+=10;reasons.push("MACD agrees with direction")};if(ax!=null&&ax>=25){score+=15;reasons.push(`ADX ${ax.toFixed(1)} shows strong trend conditions`)}else if(ax!=null&&ax>=20){score+=8;reasons.push(`ADX ${ax.toFixed(1)} shows moderate trend conditions`)}if(sw.highs.length>=2&&sw.lows.length>=2){const hh=sw.highs.at(-1)>sw.highs.at(-2),hl=sw.lows.at(-1)>sw.lows.at(-2),lh=sw.highs.at(-1)<sw.highs.at(-2),ll=sw.lows.at(-1)<sw.lows.at(-2);if((direction==="BUY"&&hh&&hl)||(direction==="SELL"&&lh&&ll)){score+=15;reasons.push(direction==="BUY"?"Market structure shows HH/HL":"Market structure shows LH/LL")}}if((direction==="BUY"&&/Bullish|Hammer/.test(pat))||(direction==="SELL"&&/Bearish|Shooting/.test(pat))){score+=10;reasons.push(`${pat} supports the direction`)}else if(pat!=="None"){score+=3;reasons.push(`${pat} detected`)}if(bands&&((direction==="BUY"&&price>bands.upper*.998)||(direction==="SELL"&&price<bands.lower*1.002))){score+=5;reasons.push("Volatility expansion is present")};score=Math.min(100,score);const label=score>=85?"HIGH-CONFLUENCE SETUP":score>=75?"STRONG SETUP":score>=60?"VALID SETUP":score>=40?"WEAK SETUP":"WAIT";let entry=null,stopLoss=null,tp1=null,tp2=null;if(score>=60&&a){const d=Math.max(a*1.2,price*.001);entry=price;if(direction==="BUY"){stopLoss=price-d;tp1=price+d*1.5;tp2=price+d*2.5}else{stopLoss=price+d;tp1=price-d*1.5;tp2=price-d*2.5}}return{direction:score>=60?direction:"WAIT",score,scoreLabel:label,price,entry,stopLoss,tp1,tp2,indicators:{rsi:rv,adx:ax,ema20:e20,ema50:e50,ema200:e200,atr:a,macd:mc,bollinger:bands,pattern:pat,structure:sw.highs.length>=2&&sw.lows.length>=2?"confirmed":"developing"},reasons,timestamp:new Date().toISOString()}}
async function signalFor(k,interval=process.env.MARKET_INTERVAL||"15min"){const cfg=INSTRUMENTS[k],d=await td("/time_series",{symbol:cfg.dataSymbol,interval,outputsize:300,timezone:"UTC"});if(!d.values?.length)throw new Error("No market data returned");const s=analyze(d.values),c=nums(d.values,"close");s.sourceSymbol=cfg.dataSymbol;s.interval=interval;s.percentChange=c.length>1?((c.at(-1)-c.at(-2))/c.at(-2))*100:0;return s}

app.get("/api/health",async(req,res)=>{let db=false;try{if(useDb){await pool.query("SELECT 1");db=true}}catch{}res.json({ok:true,serverTime:new Date().toISOString(),twelveDataConfigured:Boolean(TD_KEY),databaseConfigured:useDb,databaseConnected:db,paypalConfigured:Boolean(process.env.PAYPAL_CLIENT_ID&&process.env.PAYPAL_CLIENT_SECRET),instruments:Object.keys(INSTRUMENTS)})});
app.get("/api/instruments",(req,res)=>res.json(INSTRUMENTS));
app.get("/api/public-prices",async(req,res)=>{if(!TD_KEY)return res.status(503).json({error:"Live data is not configured yet."});const keys=Object.keys(INSTRUMENTS);const out={};await Promise.all(keys.map(async k=>{try{const d=await td("/price",{symbol:INSTRUMENTS[k].dataSymbol});out[k]={price:Number(d.price),sourceSymbol:INSTRUMENTS[k].dataSymbol}}catch(e){out[k]={price:null,error:e.message}}}));res.json(out)});

app.post("/api/auth/register",async(req,res)=>{try{const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:"Enter a valid email address."});if(password.length<8)return res.status(400).json({error:"Password must be at least 8 characters."});if(await getUserByEmail(email))return res.status(409).json({error:"An account with this email already exists. Log in instead."});const u=await createUser(email,password);res.status(201).json({ok:true,message:"Account created. Purchase membership to unlock the dashboard.",token:issueSession(u),member:{email:u.email,plan:u.plan,status:u.status}})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/auth/login",async(req,res)=>{try{const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");const u=await getUserByEmail(email);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:"Incorrect email or password."});res.json({ok:true,token:issueSession(u),member:{email:u.email,plan:u.plan,status:u.status}})}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/member/me",auth,(req,res)=>res.json({member:{email:req.user.email,plan:req.user.plan,status:req.user.status,createdAt:req.user.created_at}}));
app.get("/api/member/signals",requireActive,async(req,res)=>{if(!TD_KEY)return res.status(503).json({error:"TWELVE_DATA_API_KEY is not configured on the server."});const out={};await Promise.all(Object.keys(INSTRUMENTS).map(async k=>{try{out[k]=await signalFor(k)}catch(e){out[k]={direction:"WAIT",score:0,scoreLabel:"DATA UNAVAILABLE",price:null,error:e.message,timestamp:new Date().toISOString()}}}));res.json(out)});
app.get("/api/strategy",(req,res)=>res.json({name:"BluEmaTrend Trade",author:"Iyaloo ‘Risky’",handle:"@riskybankss",introductoryPrice:20,regularPrice:200,priceChangeDate:"2027-01-01",document:"/downloads/BluEmaTrend_Trade_Polished.docx"}));

function paypalBase(){return process.env.PAYPAL_ENV==="sandbox"?"https://api-m.sandbox.paypal.com":"https://api-m.paypal.com"}
async function paypalToken(){if(!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)throw new Error("PayPal is not configured on the server.");const auth=Buffer.from(`${process.env.PAYPAL_CLIENT_ID}:${process.env.PAYPAL_CLIENT_SECRET}`).toString("base64"),r=await fetch(`${paypalBase()}/v1/oauth2/token`,{method:"POST",headers:{Authorization:`Basic ${auth}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"}),j=await r.json();if(!r.ok)throw new Error(j.error_description||"PayPal authentication failed");return{token:j.access_token,base:paypalBase()}}
function lifetimePrice(){const now=new Date();return now<new Date("2027-01-01T00:00:00Z")?"20.00":"200.00"}
app.post("/api/paypal/order",auth,async(req,res)=>{try{const plan=req.body?.plan;if(!["lifetime","monthly"].includes(plan))return res.status(400).json({error:"Choose a valid membership."});const pp=await paypalToken();if(plan==="monthly"){if(!process.env.PAYPAL_MONTHLY_PLAN_ID)throw new Error("PAYPAL_MONTHLY_PLAN_ID is not configured.");const r=await fetch(`${pp.base}/v1/billing/subscriptions`,{method:"POST",headers:{Authorization:`Bearer ${pp.token}`,"Content-Type":"application/json"},body:JSON.stringify({plan_id:process.env.PAYPAL_MONTHLY_PLAN_ID,custom_id:req.user.email,application_context:{brand_name:"QUANT-ALPHA",user_action:"SUBSCRIBE_NOW",return_url:`${APP_URL}/?payment=subscription&subscription_id={subscription_id}`,cancel_url:`${APP_URL}/?payment=cancelled`}})}),j=await r.json();if(!r.ok)throw new Error(j.message||"Unable to create subscription");await updateUser(req.user.id,{paypal_subscription_id:j.id});return res.json({id:j.id,approveUrl:j.links?.find(x=>x.rel==="approve")?.href})}
const price=lifetimePrice(),r=await fetch(`${pp.base}/v2/checkout/orders`,{method:"POST",headers:{Authorization:`Bearer ${pp.token}`,"Content-Type":"application/json"},body:JSON.stringify({intent:"CAPTURE",purchase_units:[{amount:{currency_code:"USD",value:price},description:`Quant-Alpha Lifetime Access (${price} USD introductory price)`}],application_context:{brand_name:"QUANT-ALPHA",user_action:"PAY_NOW",return_url:`${APP_URL}/?payment=success`,cancel_url:`${APP_URL}/?payment=cancelled`}})}),j=await r.json();if(!r.ok)throw new Error(j.message||"Unable to create PayPal order");await updateUser(req.user.id,{paypal_order_id:j.id});res.json({id:j.id,price,approveUrl:j.links?.find(x=>x.rel==="approve")?.href})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/paypal/capture",auth,async(req,res)=>{try{const orderId=req.body?.orderId;if(!orderId)return res.status(400).json({error:"Missing PayPal order ID."});if(req.user.paypal_order_id&&req.user.paypal_order_id!==orderId)return res.status(400).json({error:"This payment does not match your account."});const pp=await paypalToken(),r=await fetch(`${pp.base}/v2/checkout/orders/${encodeURIComponent(orderId)}/capture`,{method:"POST",headers:{Authorization:`Bearer ${pp.token}`,"Content-Type":"application/json"}}),j=await r.json();if(!r.ok||j.status!=="COMPLETED")return res.status(400).json({error:j.message||"Payment not completed."});const u=await updateUser(req.user.id,{plan:"lifetime",status:"active",paypal_order_id:orderId});res.json({ok:true,token:issueSession(u),member:{email:u.email,plan:u.plan,status:u.status}})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/paypal/subscription/activate",auth,async(req,res)=>{try{const id=req.body?.subscriptionId;if(!id)return res.status(400).json({error:"Missing subscription ID."});const pp=await paypalToken(),r=await fetch(`${pp.base}/v1/billing/subscriptions/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${pp.token}`,Accept:"application/json"}}),j=await r.json();if(!r.ok||j.status!=="ACTIVE")return res.status(400).json({error:`Subscription status is ${j.status||"unknown"}.`});const u=await updateUser(req.user.id,{plan:"monthly",status:"active",paypal_subscription_id:id});res.json({ok:true,token:issueSession(u),member:{email:u.email,plan:u.plan,status:u.status}})}catch(e){res.status(500).json({error:e.message})}});

app.get("/dashboard",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.get("/{*splat}",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));

initDb().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log(`QUANT-ALPHA V4 listening on ${PORT} | DB=${useDb} | TD=${Boolean(TD_KEY)}`))).catch(e=>{console.error(e);process.exit(1)});
